language: python
python:
- '2.7'
install:
- pip install --upgrade -e .
- python setup.py install
script:
- echo "Tests skipped"
deploy:
  provider: pypi
  user: opennode
  password:
    secure: q2c9tqME8mGM1RLNUUrJH0zVE/Vu6fOajHiklTmZcTslvt9phjbHySNfDijJeaf1BS7+lRu9mfPEf9wsDb3NT15MRArBNPMkz0lxESfaU/j5jZLKFZSgLGpZ97InZ0Oe8HW/UdAgQ4dp2ZFH67YQBNV4lAnqAEzGV/wN03RtxCOwdC4orDhR6/UZiV07jJeWA08cHvPeuHUJLseRy20rzTpFHAKBfvXzww5waCdAqDT0cAUOy8tyZOoOmqDgrVJIkH2WH1/C5T7BmFhdJfXfuQJbj6BYq5jZU8fuj9c+qaE9440jRXxWhvJfDwGb766GYp2WdYsUFqpIQZLpUclI5OnHs9GhxVGzGNbhQLCjgo588MMfi1BjOiYr2s74JtCIvLIF/sYbAaCKend5jeAYYpTRA6m60BqxjbxOU3QzLwxKGhE1cAk3ysMNx1Y6RwYlou6ZlZWLE5gNTVZB6k0zeIUlVDckqC5Hr930+pOvsh4xBFaFSfD2JO5REPkOqArNyU3HOeHyIbCqsFdB7w8mbrFYRciTUXyD4FXOPM+TvCxSJZ58/m7RZ6haTndOMGIYPlTy12D/nipUT0ouQqKakStJPovFr4Rd1EgCHmccHcZDJMpaS8TtCu0CGZnD+t1AADp/QnyPmAQsOrIquY6CMrsdH9lgTPmR+1hjPf8L9DU=
  on:
    tags: true
    repo: opennode/ansible-waldur-module
  distributions: "sdist bdist_wheel"
