- role: CUSTOMER.OWNER
  description: Organization owner
  permissions:
    - OFFERING.CREATE
    - OFFERING.DELETE
    - OFFERING.UPDATE
    - OFFERING.UPDATE_THUMBNAIL
    - OFFERING.UPDATE_ATTRIBUTES
    - OFFERING.UPDATE_LOCATION
    - OFFERING.UPDATE_DESCRIPTION
    - OFFERING.UPDATE_OPTIONS
    - OFFERING.UPDATE_INTEGRATION
    - OFFERING.ADD_ENDPOINT
    - OFFERING.DELETE_ENDPOINT
    - OFFERING.UPDATE_COMPONENTS
    - OFFERING.PAUSE
    - OFFERING.UNPAUSE
    - OFFERING.ARCHIVE
    - OFFERING.DRY_RUN_SCRIPT
    - OFFERING.MANAGE_CAMPAIGN
    - OFFERING.MANAGE_USER_GROUP
    - OFFERING.CREATE_PLAN
    - OFFERING.UPDATE_PLAN
    - OFFERING.ARCHIVE_PLAN
    - OFFERING.CREATE_SCREENSHOT
    - OFFERING.UPDATE_SCREENSHOT
    - OFFERING.DELETE_SCREENSHOT
    - OFFERING.CREATE_USER
    - OFFERING.MANAGE_USER_ROLE
    - RESOURCE.MANAGE_USERS
    - ORDER.APPROVE
    - ORDER.APPROVE_PRIVATE
    - ORDER.REJECT
    - ORDER.DESTROY
    - ORDER.CANCEL
    - RESOURCE.SET_END_DATE
    - RESOURCE.SET_USAGE
    - RESOURCE.SET_PLAN
    - RESOURCE.UPDATE_OPTIONS
    - RESOURCE.SET_LIMITS
    - RESOURCE.SET_BACKEND_ID
    - RESOURCE.ACCEPT_BOOKING_REQUEST
    - RESOURCE.REJECT_BOOKING_REQUEST
    - RESOURCE.SUBMIT_REPORT
    - RESOURCE.LIST_USERS
    - RESOURCE.COMPLETE_DOWNSCALING
    - RESOURCE.TERMINATE
    - RESOURCE.LIST_IMPORTABLE
    - RESOURCE.CREATE_ROBOT_ACCOUNT
    - RESOURCE.UPDATE_ROBOT_ACCOUNT
    - RESOURCE.DELETE_ROBOT_ACCOUNT
    - PROJECT.CREATE_PERMISSION
    - PROJECT.UPDATE_PERMISSION
    - PROJECT.DELETE_PERMISSION
    - OFFERING.CREATE_PERMISSION
    - OFFERING.UPDATE_PERMISSION
    - OFFERING.DELETE_PERMISSION
    - PROJECT.CREATE
    - PROJECT.UPDATE
    - PROJECT.DELETE
    - OFFERING.ACCEPT_CALL_REQUEST

- role: CUSTOMER.MANAGER
  description: Organization manager
  permissions:
    - RESOURCE.SET_END_DATE
    - RESOURCE.SET_BACKEND_ID
    - RESOURCE.ACCEPT_BOOKING_REQUEST
    - RESOURCE.REJECT_BOOKING_REQUEST
    - RESOURCE.SUBMIT_REPORT
    - RESOURCE.LIST_USERS
    - RESOURCE.COMPLETE_DOWNSCALING
    - RESOURCE.CREATE_ROBOT_ACCOUNT
    - RESOURCE.UPDATE_ROBOT_ACCOUNT
    - RESOURCE.DELETE_ROBOT_ACCOUNT
    - OFFERING.UPDATE_THUMBNAIL
    - OFFERING.UPDATE_ATTRIBUTES
    - OFFERING.UPDATE_LOCATION
    - OFFERING.UPDATE_DESCRIPTION
    - OFFERING.UPDATE
    - OFFERING.UPDATE_OPTIONS
    - OFFERING.UPDATE_INTEGRATION
    - OFFERING.ADD_ENDPOINT
    - OFFERING.DELETE_ENDPOINT
    - OFFERING.UPDATE_COMPONENTS
    - OFFERING.PAUSE
    - OFFERING.UNPAUSE
    - OFFERING.ARCHIVE
    - OFFERING.DRY_RUN_SCRIPT
    - OFFERING.MANAGE_CAMPAIGN
    - OFFERING.MANAGE_USER_GROUP

- role: PROJECT.ADMIN
  description: Project administrator
  permissions:
    - ORDER.APPROVE_PRIVATE
    - ORDER.DESTROY
    - ORDER.CANCEL
    - RESOURCE.TERMINATE
    - RESOURCE.LIST_IMPORTABLE
    - RESOURCE.SET_PLAN
    - RESOURCE.UPDATE_OPTIONS
    - RESOURCE.SET_LIMITS

- role: PROJECT.MANAGER
  description: Project manager
  permissions:
    - ORDER.APPROVE_PRIVATE
    - ORDER.DESTROY
    - ORDER.CANCEL
    - RESOURCE.TERMINATE
    - RESOURCE.LIST_IMPORTABLE
    - RESOURCE.SET_PLAN
    - RESOURCE.UPDATE_OPTIONS
    - RESOURCE.SET_LIMITS
    - PROJECT.CREATE_PERMISSION
    - PROJECT.UPDATE_PERMISSION
    - PROJECT.DELETE_PERMISSION
    - PROJECT.UPDATE

- role: OFFERING.MANAGEpR
  description: Offering manager
  permissions:
    - OFFERING.UPDATE
    - OFFERING.UPDATE_ATTRIBUTES
    - OFFERING.UPDATE_LOCATION
    - OFFERING.UPDATE_DESCRIPTION
    - OFFERING.UPDATE_OPTIONS
    - OFFERING.UPDATE_INTEGRATION
    - OFFERING.ADD_ENDPOINT
    - OFFERING.DELETE_ENDPOINT
    - OFFERING.UPDATE_COMPONENTS
    - OFFERING.PAUSE
    - OFFERING.UNPAUSE
    - OFFERING.ARCHIVE
    - OFFERING.DRY_RUN_SCRIPT
    - RESOURCE.SET_USAGE
    - RESOURCE.SET_BACKEND_ID
    - RESOURCE.ACCEPT_BOOKING_REQUEST
    - RESOURCE.REJECT_BOOKING_REQUEST
    - OFFERING.ACCEPT_CALL_REQUEST

- role: CALL.REVIEWER
  description: Call reviewer
  permissions: []
