site_name: ""
site_address: ""
site_email: ""
site_phone: ""
short_page_title: ""
full_page_title: ""
brand_color: ""
brand_label_color: ""
hero_link_label: ""
hero_link_url: ""
site_description: ""
currency_name: ""
docs_url: ""
support_portal_url: ""
powered_by_logo: ""
hero_image: ""
sidebar_logo: ""
sidebar_logo_mobile: ""
site_logo: ""
login_logo: ""
favicon: ""
